# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (3, 0, 0):
    new_instancemethod = lambda func, inst, cls: _emerlinmusicplayer.SWIG_PyInstanceMethod_New(func)
else:
    from new import instancemethod as new_instancemethod
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_emerlinmusicplayer')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_emerlinmusicplayer')
    _emerlinmusicplayer = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_emerlinmusicplayer', [dirname(__file__)])
        except ImportError:
            import _emerlinmusicplayer
            return _emerlinmusicplayer
        try:
            _mod = imp.load_module('_emerlinmusicplayer', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _emerlinmusicplayer = swig_import_helper()
    del swig_import_helper
else:
    import _emerlinmusicplayer
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_method(set):
    def set_attr(self, name, value):
        if (name == "thisown"):
            return self.this.own(value)
        if hasattr(self, name) or (name == "this"):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


try:
    import weakref
    weakref_proxy = weakref.proxy
except __builtin__.Exception:
    weakref_proxy = lambda x: x


import enigma
class MerlinPairVector(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    def __iter__(self):
        return self.iterator()

    def __init__(self, *args):
        _emerlinmusicplayer.MerlinPairVector_swiginit(self, _emerlinmusicplayer.new_MerlinPairVector(*args))
    __swig_destroy__ = _emerlinmusicplayer.delete_MerlinPairVector
MerlinPairVector.iterator = new_instancemethod(_emerlinmusicplayer.MerlinPairVector_iterator, None, MerlinPairVector)
MerlinPairVector.__nonzero__ = new_instancemethod(_emerlinmusicplayer.MerlinPairVector___nonzero__, None, MerlinPairVector)
MerlinPairVector.__bool__ = new_instancemethod(_emerlinmusicplayer.MerlinPairVector___bool__, None, MerlinPairVector)
MerlinPairVector.__len__ = new_instancemethod(_emerlinmusicplayer.MerlinPairVector___len__, None, MerlinPairVector)
MerlinPairVector.__getslice__ = new_instancemethod(_emerlinmusicplayer.MerlinPairVector___getslice__, None, MerlinPairVector)
MerlinPairVector.__setslice__ = new_instancemethod(_emerlinmusicplayer.MerlinPairVector___setslice__, None, MerlinPairVector)
MerlinPairVector.__delslice__ = new_instancemethod(_emerlinmusicplayer.MerlinPairVector___delslice__, None, MerlinPairVector)
MerlinPairVector.__delitem__ = new_instancemethod(_emerlinmusicplayer.MerlinPairVector___delitem__, None, MerlinPairVector)
MerlinPairVector.__getitem__ = new_instancemethod(_emerlinmusicplayer.MerlinPairVector___getitem__, None, MerlinPairVector)
MerlinPairVector.__setitem__ = new_instancemethod(_emerlinmusicplayer.MerlinPairVector___setitem__, None, MerlinPairVector)
MerlinPairVector.pop = new_instancemethod(_emerlinmusicplayer.MerlinPairVector_pop, None, MerlinPairVector)
MerlinPairVector.append = new_instancemethod(_emerlinmusicplayer.MerlinPairVector_append, None, MerlinPairVector)
MerlinPairVector.empty = new_instancemethod(_emerlinmusicplayer.MerlinPairVector_empty, None, MerlinPairVector)
MerlinPairVector.size = new_instancemethod(_emerlinmusicplayer.MerlinPairVector_size, None, MerlinPairVector)
MerlinPairVector.swap = new_instancemethod(_emerlinmusicplayer.MerlinPairVector_swap, None, MerlinPairVector)
MerlinPairVector.begin = new_instancemethod(_emerlinmusicplayer.MerlinPairVector_begin, None, MerlinPairVector)
MerlinPairVector.end = new_instancemethod(_emerlinmusicplayer.MerlinPairVector_end, None, MerlinPairVector)
MerlinPairVector.rbegin = new_instancemethod(_emerlinmusicplayer.MerlinPairVector_rbegin, None, MerlinPairVector)
MerlinPairVector.rend = new_instancemethod(_emerlinmusicplayer.MerlinPairVector_rend, None, MerlinPairVector)
MerlinPairVector.clear = new_instancemethod(_emerlinmusicplayer.MerlinPairVector_clear, None, MerlinPairVector)
MerlinPairVector.get_allocator = new_instancemethod(_emerlinmusicplayer.MerlinPairVector_get_allocator, None, MerlinPairVector)
MerlinPairVector.pop_back = new_instancemethod(_emerlinmusicplayer.MerlinPairVector_pop_back, None, MerlinPairVector)
MerlinPairVector.erase = new_instancemethod(_emerlinmusicplayer.MerlinPairVector_erase, None, MerlinPairVector)
MerlinPairVector.push_back = new_instancemethod(_emerlinmusicplayer.MerlinPairVector_push_back, None, MerlinPairVector)
MerlinPairVector.front = new_instancemethod(_emerlinmusicplayer.MerlinPairVector_front, None, MerlinPairVector)
MerlinPairVector.back = new_instancemethod(_emerlinmusicplayer.MerlinPairVector_back, None, MerlinPairVector)
MerlinPairVector.assign = new_instancemethod(_emerlinmusicplayer.MerlinPairVector_assign, None, MerlinPairVector)
MerlinPairVector.resize = new_instancemethod(_emerlinmusicplayer.MerlinPairVector_resize, None, MerlinPairVector)
MerlinPairVector.insert = new_instancemethod(_emerlinmusicplayer.MerlinPairVector_insert, None, MerlinPairVector)
MerlinPairVector.reserve = new_instancemethod(_emerlinmusicplayer.MerlinPairVector_reserve, None, MerlinPairVector)
MerlinPairVector.capacity = new_instancemethod(_emerlinmusicplayer.MerlinPairVector_capacity, None, MerlinPairVector)
MerlinPairVector_swigregister = _emerlinmusicplayer.MerlinPairVector_swigregister
MerlinPairVector_swigregister(MerlinPairVector)

from enigma import WeakMethodReference

MAX_RETRIES = _emerlinmusicplayer.MAX_RETRIES
VIDEO_STREAMTYPE_MPEG2 = _emerlinmusicplayer.VIDEO_STREAMTYPE_MPEG2
class eMerlinMusicPlayerRMSSlider(enigma.eSlider):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, parent):
        _emerlinmusicplayer.eMerlinMusicPlayerRMSSlider_swiginit(self, _emerlinmusicplayer.new_eMerlinMusicPlayerRMSSlider(parent))
    __swig_destroy__ = _emerlinmusicplayer.delete_eMerlinMusicPlayerRMSSlider
    modeStandardEnigmaSlider = _emerlinmusicplayer.eMerlinMusicPlayerRMSSlider_modeStandardEnigmaSlider
    modeImagesOrientationUp = _emerlinmusicplayer.eMerlinMusicPlayerRMSSlider_modeImagesOrientationUp
    modeSingleImageOrientationUp = _emerlinmusicplayer.eMerlinMusicPlayerRMSSlider_modeSingleImageOrientationUp
    modeImagesOrientationLeft = _emerlinmusicplayer.eMerlinMusicPlayerRMSSlider_modeImagesOrientationLeft
    modeSingleImageOrientationLeft = _emerlinmusicplayer.eMerlinMusicPlayerRMSSlider_modeSingleImageOrientationLeft
    modeCircle = _emerlinmusicplayer.eMerlinMusicPlayerRMSSlider_modeCircle
    modeArc = _emerlinmusicplayer.eMerlinMusicPlayerRMSSlider_modeArc
    modeImagesOrientationDown = _emerlinmusicplayer.eMerlinMusicPlayerRMSSlider_modeImagesOrientationDown
    modeImagesOrientationRight = _emerlinmusicplayer.eMerlinMusicPlayerRMSSlider_modeImagesOrientationRight
    modeSquare = _emerlinmusicplayer.eMerlinMusicPlayerRMSSlider_modeSquare
    modeImageRMSPeakUp = _emerlinmusicplayer.eMerlinMusicPlayerRMSSlider_modeImageRMSPeakUp
    modeImageRMSPeakDown = _emerlinmusicplayer.eMerlinMusicPlayerRMSSlider_modeImageRMSPeakDown
    modeImageRMSPeakLeft = _emerlinmusicplayer.eMerlinMusicPlayerRMSSlider_modeImageRMSPeakLeft
    modeImageRMSPeakRight = _emerlinmusicplayer.eMerlinMusicPlayerRMSSlider_modeImageRMSPeakRight
    modeVUMeter = _emerlinmusicplayer.eMerlinMusicPlayerRMSSlider_modeVUMeter
eMerlinMusicPlayerRMSSlider.setChannel = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayerRMSSlider_setChannel, None, eMerlinMusicPlayerRMSSlider)
eMerlinMusicPlayerRMSSlider.setMode = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayerRMSSlider_setMode, None, eMerlinMusicPlayerRMSSlider)
eMerlinMusicPlayerRMSSlider.setMaxValue = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayerRMSSlider_setMaxValue, None, eMerlinMusicPlayerRMSSlider)
eMerlinMusicPlayerRMSSlider.setPixmap1 = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayerRMSSlider_setPixmap1, None, eMerlinMusicPlayerRMSSlider)
eMerlinMusicPlayerRMSSlider.setBackgroundPixmap1 = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayerRMSSlider_setBackgroundPixmap1, None, eMerlinMusicPlayerRMSSlider)
eMerlinMusicPlayerRMSSlider.setDistance = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayerRMSSlider_setDistance, None, eMerlinMusicPlayerRMSSlider)
eMerlinMusicPlayerRMSSlider.setSmoothValue = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayerRMSSlider_setSmoothValue, None, eMerlinMusicPlayerRMSSlider)
eMerlinMusicPlayerRMSSlider.setBackgroundPixmapColor1 = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayerRMSSlider_setBackgroundPixmapColor1, None, eMerlinMusicPlayerRMSSlider)
eMerlinMusicPlayerRMSSlider.setThreshold1 = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayerRMSSlider_setThreshold1, None, eMerlinMusicPlayerRMSSlider)
eMerlinMusicPlayerRMSSlider.setThreshold2 = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayerRMSSlider_setThreshold2, None, eMerlinMusicPlayerRMSSlider)
eMerlinMusicPlayerRMSSlider.setDrawBackground = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayerRMSSlider_setDrawBackground, None, eMerlinMusicPlayerRMSSlider)
eMerlinMusicPlayerRMSSlider.setBlendColor = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayerRMSSlider_setBlendColor, None, eMerlinMusicPlayerRMSSlider)
eMerlinMusicPlayerRMSSlider.setClockwise = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayerRMSSlider_setClockwise, None, eMerlinMusicPlayerRMSSlider)
eMerlinMusicPlayerRMSSlider.setStartAngle = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayerRMSSlider_setStartAngle, None, eMerlinMusicPlayerRMSSlider)
eMerlinMusicPlayerRMSSlider.setArcAngle = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayerRMSSlider_setArcAngle, None, eMerlinMusicPlayerRMSSlider)
eMerlinMusicPlayerRMSSlider.setFadeOutTime = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayerRMSSlider_setFadeOutTime, None, eMerlinMusicPlayerRMSSlider)
eMerlinMusicPlayerRMSSlider.setVUMeterPictureLocation = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayerRMSSlider_setVUMeterPictureLocation, None, eMerlinMusicPlayerRMSSlider)
eMerlinMusicPlayerRMSSlider.setVUMeterPictureAxis = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayerRMSSlider_setVUMeterPictureAxis, None, eMerlinMusicPlayerRMSSlider)
eMerlinMusicPlayerRMSSlider.setVUMeterAttackValue = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayerRMSSlider_setVUMeterAttackValue, None, eMerlinMusicPlayerRMSSlider)
eMerlinMusicPlayerRMSSlider.setAdaption = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayerRMSSlider_setAdaption, None, eMerlinMusicPlayerRMSSlider)
eMerlinMusicPlayerRMSSlider_swigregister = _emerlinmusicplayer.eMerlinMusicPlayerRMSSlider_swigregister
eMerlinMusicPlayerRMSSlider_swigregister(eMerlinMusicPlayerRMSSlider)

class eMerlinMusicPlayerWidget(enigma.eWidget):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, parent):
        _emerlinmusicplayer.eMerlinMusicPlayerWidget_swiginit(self, _emerlinmusicplayer.new_eMerlinMusicPlayerWidget(parent))
    __swig_destroy__ = _emerlinmusicplayer.delete_eMerlinMusicPlayerWidget
    modeVisUpDown = _emerlinmusicplayer.eMerlinMusicPlayerWidget_modeVisUpDown
    modeVisRoundCover = _emerlinmusicplayer.eMerlinMusicPlayerWidget_modeVisRoundCover
    modeStandardCover = _emerlinmusicplayer.eMerlinMusicPlayerWidget_modeStandardCover
    modeVisUp = _emerlinmusicplayer.eMerlinMusicPlayerWidget_modeVisUp
    modeBlendCover = _emerlinmusicplayer.eMerlinMusicPlayerWidget_modeBlendCover
    modeVisImagesUp = _emerlinmusicplayer.eMerlinMusicPlayerWidget_modeVisImagesUp
    modeVisImagesDown = _emerlinmusicplayer.eMerlinMusicPlayerWidget_modeVisImagesDown
    modeVisGLWaves = _emerlinmusicplayer.eMerlinMusicPlayerWidget_modeVisGLWaves
    modeVisGLEclipse = _emerlinmusicplayer.eMerlinMusicPlayerWidget_modeVisGLEclipse
    modeVisGLBalls = _emerlinmusicplayer.eMerlinMusicPlayerWidget_modeVisGLBalls
    modeVisGLDots = _emerlinmusicplayer.eMerlinMusicPlayerWidget_modeVisGLDots
    modeVisGLSinus = _emerlinmusicplayer.eMerlinMusicPlayerWidget_modeVisGLSinus
    modeVisGLRandom = _emerlinmusicplayer.eMerlinMusicPlayerWidget_modeVisGLRandom
eMerlinMusicPlayerWidget.setAspectRatio = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayerWidget_setAspectRatio, None, eMerlinMusicPlayerWidget)
eMerlinMusicPlayerWidget.setCover = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayerWidget_setCover, None, eMerlinMusicPlayerWidget)
eMerlinMusicPlayerWidget.setMode = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayerWidget_setMode, None, eMerlinMusicPlayerWidget)
eMerlinMusicPlayerWidget.setNoCoverPic = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayerWidget_setNoCoverPic, None, eMerlinMusicPlayerWidget)
eMerlinMusicPlayerWidget.setPixmap1 = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayerWidget_setPixmap1, None, eMerlinMusicPlayerWidget)
eMerlinMusicPlayerWidget.setPixmap2 = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayerWidget_setPixmap2, None, eMerlinMusicPlayerWidget)
eMerlinMusicPlayerWidget.setDistance1 = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayerWidget_setDistance1, None, eMerlinMusicPlayerWidget)
eMerlinMusicPlayerWidget.setDistance2 = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayerWidget_setDistance2, None, eMerlinMusicPlayerWidget)
eMerlinMusicPlayerWidget.setThreshold1 = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayerWidget_setThreshold1, None, eMerlinMusicPlayerWidget)
eMerlinMusicPlayerWidget.setThreshold2 = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayerWidget_setThreshold2, None, eMerlinMusicPlayerWidget)
eMerlinMusicPlayerWidget.setMaxValue = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayerWidget_setMaxValue, None, eMerlinMusicPlayerWidget)
eMerlinMusicPlayerWidget.setSmoothValue = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayerWidget_setSmoothValue, None, eMerlinMusicPlayerWidget)
eMerlinMusicPlayerWidget.setInternalSize = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayerWidget_setInternalSize, None, eMerlinMusicPlayerWidget)
eMerlinMusicPlayerWidget.setBlendColor = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayerWidget_setBlendColor, None, eMerlinMusicPlayerWidget)
eMerlinMusicPlayerWidget.setDrawBackground = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayerWidget_setDrawBackground, None, eMerlinMusicPlayerWidget)
eMerlinMusicPlayerWidget.setBackgroundPixmapColor1 = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayerWidget_setBackgroundPixmapColor1, None, eMerlinMusicPlayerWidget)
eMerlinMusicPlayerWidget.setBackgroundPixmap2 = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayerWidget_setBackgroundPixmap2, None, eMerlinMusicPlayerWidget)
eMerlinMusicPlayerWidget.setFadeOutTime = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayerWidget_setFadeOutTime, None, eMerlinMusicPlayerWidget)
eMerlinMusicPlayerWidget.visGLRandomPause = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayerWidget_visGLRandomPause, None, eMerlinMusicPlayerWidget)
eMerlinMusicPlayerWidget.visGLRandomNext = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayerWidget_visGLRandomNext, None, eMerlinMusicPlayerWidget)
eMerlinMusicPlayerWidget.visGLRandomStart = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayerWidget_visGLRandomStart, None, eMerlinMusicPlayerWidget)
eMerlinMusicPlayerWidget_swigregister = _emerlinmusicplayer.eMerlinMusicPlayerWidget_swigregister
eMerlinMusicPlayerWidget_swigregister(eMerlinMusicPlayerWidget)

class eMerlinMusicPlayer(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self):
        _emerlinmusicplayer.eMerlinMusicPlayer_swiginit(self, _emerlinmusicplayer.new_eMerlinMusicPlayer())
    __swig_destroy__ = _emerlinmusicplayer.delete_eMerlinMusicPlayer
    getInstance = staticmethod(_emerlinmusicplayer.eMerlinMusicPlayer_getInstance)
eMerlinMusicPlayer.setFunc = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayer_setFunc, None, eMerlinMusicPlayer)
eMerlinMusicPlayer.show_iFrame_Pic = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayer_show_iFrame_Pic, None, eMerlinMusicPlayer)
eMerlinMusicPlayer.enableGapless = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayer_enableGapless, None, eMerlinMusicPlayer)
eMerlinMusicPlayer.enableAlsa = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayer_enableAlsa, None, eMerlinMusicPlayer)
eMerlinMusicPlayer.enableEqualizer = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayer_enableEqualizer, None, eMerlinMusicPlayer)
eMerlinMusicPlayer.setEqualizerData = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayer_setEqualizerData, None, eMerlinMusicPlayer)
eMerlinMusicPlayer_swigregister = _emerlinmusicplayer.eMerlinMusicPlayer_swigregister
eMerlinMusicPlayer_swigregister(eMerlinMusicPlayer)

def eMerlinMusicPlayer_getInstance():
    return _emerlinmusicplayer.eMerlinMusicPlayer_getInstance()
eMerlinMusicPlayer_getInstance = _emerlinmusicplayer.eMerlinMusicPlayer_getInstance

class eMerlinMusicPlayerRecorder(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self):
        _emerlinmusicplayer.eMerlinMusicPlayerRecorder_swiginit(self, _emerlinmusicplayer.new_eMerlinMusicPlayerRecorder())
    __swig_destroy__ = _emerlinmusicplayer.delete_eMerlinMusicPlayerRecorder
    m_event = _swig_property(_emerlinmusicplayer.eMerlinMusicPlayerRecorder_m_event_get, _emerlinmusicplayer.eMerlinMusicPlayerRecorder_m_event_set)
    evRecordRunning = _emerlinmusicplayer.eMerlinMusicPlayerRecorder_evRecordRunning
    evRecordStopped = _emerlinmusicplayer.eMerlinMusicPlayerRecorder_evRecordStopped
    evRecordFailed = _emerlinmusicplayer.eMerlinMusicPlayerRecorder_evRecordFailed
eMerlinMusicPlayerRecorder.start = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayerRecorder_start, None, eMerlinMusicPlayerRecorder)
eMerlinMusicPlayerRecorder.stop = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayerRecorder_stop, None, eMerlinMusicPlayerRecorder)
eMerlinMusicPlayerRecorder.isRecording = new_instancemethod(_emerlinmusicplayer.eMerlinMusicPlayerRecorder_isRecording, None, eMerlinMusicPlayerRecorder)
eMerlinMusicPlayerRecorder_swigregister = _emerlinmusicplayer.eMerlinMusicPlayerRecorder_swigregister
eMerlinMusicPlayerRecorder_swigregister(eMerlinMusicPlayerRecorder)

class eServiceMerlinMP3Player_ENUMS(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    evAudioDecodeError = _emerlinmusicplayer.eServiceMerlinMP3Player_ENUMS_evAudioDecodeError
    evVideoDecodeError = _emerlinmusicplayer.eServiceMerlinMP3Player_ENUMS_evVideoDecodeError
    evPluginError = _emerlinmusicplayer.eServiceMerlinMP3Player_ENUMS_evPluginError
    evEmbeddedCoverArt = _emerlinmusicplayer.eServiceMerlinMP3Player_ENUMS_evEmbeddedCoverArt
    evUpdatedBitrate = _emerlinmusicplayer.eServiceMerlinMP3Player_ENUMS_evUpdatedBitrate
    evStreamingSrcError = _emerlinmusicplayer.eServiceMerlinMP3Player_ENUMS_evStreamingSrcError
    evFileReadError = _emerlinmusicplayer.eServiceMerlinMP3Player_ENUMS_evFileReadError
    evTypeNotFoundError = _emerlinmusicplayer.eServiceMerlinMP3Player_ENUMS_evTypeNotFoundError
    evGeneralGstError = _emerlinmusicplayer.eServiceMerlinMP3Player_ENUMS_evGeneralGstError
    evDurationChanged = _emerlinmusicplayer.eServiceMerlinMP3Player_ENUMS_evDurationChanged
    evStreamStart = _emerlinmusicplayer.eServiceMerlinMP3Player_ENUMS_evStreamStart
eServiceMerlinMP3Player_ENUMS_swigregister = _emerlinmusicplayer.eServiceMerlinMP3Player_ENUMS_swigregister
eServiceMerlinMP3Player_ENUMS_swigregister(eServiceMerlinMP3Player_ENUMS)

eServiceMerlinMP3Player = eServiceMerlinMP3Player_ENUMS
class eMerlinVideoPlayer(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self):
        _emerlinmusicplayer.eMerlinVideoPlayer_swiginit(self, _emerlinmusicplayer.new_eMerlinVideoPlayer())
    __swig_destroy__ = _emerlinmusicplayer.delete_eMerlinVideoPlayer
eMerlinVideoPlayer.isPlaying = new_instancemethod(_emerlinmusicplayer.eMerlinVideoPlayer_isPlaying, None, eMerlinVideoPlayer)
eMerlinVideoPlayer.play = new_instancemethod(_emerlinmusicplayer.eMerlinVideoPlayer_play, None, eMerlinVideoPlayer)
eMerlinVideoPlayer.stop = new_instancemethod(_emerlinmusicplayer.eMerlinVideoPlayer_stop, None, eMerlinVideoPlayer)
eMerlinVideoPlayer.volumeUp = new_instancemethod(_emerlinmusicplayer.eMerlinVideoPlayer_volumeUp, None, eMerlinVideoPlayer)
eMerlinVideoPlayer.volumeDown = new_instancemethod(_emerlinmusicplayer.eMerlinVideoPlayer_volumeDown, None, eMerlinVideoPlayer)
eMerlinVideoPlayer.setVolume = new_instancemethod(_emerlinmusicplayer.eMerlinVideoPlayer_setVolume, None, eMerlinVideoPlayer)
eMerlinVideoPlayer.volumeMute = new_instancemethod(_emerlinmusicplayer.eMerlinVideoPlayer_volumeMute, None, eMerlinVideoPlayer)
eMerlinVideoPlayer.volumeUnMute = new_instancemethod(_emerlinmusicplayer.eMerlinVideoPlayer_volumeUnMute, None, eMerlinVideoPlayer)
eMerlinVideoPlayer.volumeToggleMute = new_instancemethod(_emerlinmusicplayer.eMerlinVideoPlayer_volumeToggleMute, None, eMerlinVideoPlayer)
eMerlinVideoPlayer.isMuted = new_instancemethod(_emerlinmusicplayer.eMerlinVideoPlayer_isMuted, None, eMerlinVideoPlayer)
eMerlinVideoPlayer.getVolume = new_instancemethod(_emerlinmusicplayer.eMerlinVideoPlayer_getVolume, None, eMerlinVideoPlayer)
eMerlinVideoPlayer_swigregister = _emerlinmusicplayer.eMerlinVideoPlayer_swigregister
eMerlinVideoPlayer_swigregister(eMerlinVideoPlayer)

class eMerlinEqualizerWidget(enigma.eWidget):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, parent):
        _emerlinmusicplayer.eMerlinEqualizerWidget_swiginit(self, _emerlinmusicplayer.new_eMerlinEqualizerWidget(parent))
    __swig_destroy__ = _emerlinmusicplayer.delete_eMerlinEqualizerWidget
eMerlinEqualizerWidget.setAspectRatio = new_instancemethod(_emerlinmusicplayer.eMerlinEqualizerWidget_setAspectRatio, None, eMerlinEqualizerWidget)
eMerlinEqualizerWidget.initialize = new_instancemethod(_emerlinmusicplayer.eMerlinEqualizerWidget_initialize, None, eMerlinEqualizerWidget)
eMerlinEqualizerWidget.setDistance = new_instancemethod(_emerlinmusicplayer.eMerlinEqualizerWidget_setDistance, None, eMerlinEqualizerWidget)
eMerlinEqualizerWidget.setValue = new_instancemethod(_emerlinmusicplayer.eMerlinEqualizerWidget_setValue, None, eMerlinEqualizerWidget)
eMerlinEqualizerWidget_swigregister = _emerlinmusicplayer.eMerlinEqualizerWidget_swigregister
eMerlinEqualizerWidget_swigregister(eMerlinEqualizerWidget)



